import {
  Baby,
  Bath,
  BedDouble,
  CarFront,
  Clock3,
  Coffee,
  CreditCard,
  Flame,
  MapPin,
  Mountain,
  Phone,
  ShieldCheck,
  ShowerHead,
  Snowflake,
  Sparkles,
  Star,
  Ticket,
  Trees,
  Tv,
  UsersRound,
  UtensilsCrossed,
  Waves,
  Accessibility,
  Wifi,
  AirVent,
  Armchair,
  ArrowUpDown,
  Award,
  BadgeCheck,
  Ban,
  BatteryCharging,
  Bell,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  Bus,
  Camera,
  Castle,
  ChefHat,
  Check,
  CircleHelp,
  Clapperboard,
  CloudSun,
  Compass,
  ConciergeBell,
  CookingPot,
  DoorOpen,
  Dumbbell,
  Fan,
  Fence,
  Flower2,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  Globe2,
  Handshake,
  Heart,
  HeartPulse,
  Heater,
  House,
  IceCreamCone,
  KeyRound,
  LampDesk,
  Laptop,
  Leaf,
  Lightbulb,
  LockKeyhole,
  Luggage,
  Mail,
  Map,
  Martini,
  Microwave,
  Music2,
  Navigation,
  Package,
  PawPrint,
  Plane,
  Plug,
  Refrigerator,
  Sailboat,
  Search,
  Ship,
  ShoppingBag,
  Smartphone,
  Sofa,
  Soup,
  Speaker,
  Sun,
  Thermometer,
  Train,
  Trash2,
  Truck,
  Umbrella,
  Video,
  WashingMachine,
  Wind,
  Wine,
  Zap,
  type LucideIcon,
} from "lucide-react";
import {
  Activity,
  AlarmClock,
  Anchor,
  Backpack,
  BadgePercent,
  BedSingle,
  Beer,
  BellRing,
  Binoculars,
  Cake,
  CalendarDays,
  CalendarCheck,
  Car,
  CarTaxiFront,
  CheckCircle2,
  CircleParking,
  ClipboardCheck,
  ClipboardList,
  Cloud,
  CloudRain,
  Coins,
  Croissant,
  CupSoda,
  DoorClosed,
  Droplets,
  Fish,
  Flag,
  Flashlight,
  Fuel,
  GalleryHorizontal,
  HandHeart,
  HandPlatter,
  Headphones,
  HeartHandshake,
  Hotel,
  Hourglass,
  Image,
  Info,
  KeySquare,
  LampCeiling,
  LampFloor,
  Languages,
  Library,
  LifeBuoy,
  Lock,
  MapPinned,
  Medal,
  Megaphone,
  Moon,
  PackageCheck,
  Palmtree,
  PartyPopper,
  PenLine,
  Percent,
  PersonStanding,
  PiggyBank,
  Pizza,
  Popcorn,
  Presentation,
  Printer,
  Projector,
  Radio,
  Receipt,
  Recycle,
  RefreshCcw,
  Rocket,
  Route,
  Salad,
  ScanFace,
  Scissors,
  ScrollText,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Signal,
  Siren,
  SlidersHorizontal,
  Smile,
  Sprout,
  SquareCheck,
  Stethoscope,
  Store,
  Sunset,
  Table,
  Tag,
  Telescope,
  Tent,
  Theater,
  ThumbsUp,
  Timer,
  Toilet,
  TrainFront,
  TramFront,
  TreePine,
  Trophy,
  UserCheck,
  Wallet,
  Warehouse,
  Wrench,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  bed: BedDouble,
  wifi: Wifi,
  parking: CarFront,
  utensils: UtensilsCrossed,
  coffee: Coffee,
  waves: Waves,
  sparkles: Sparkles,
  tv: Tv,
  snowflake: Snowflake,
  mountain: Mountain,
  trees: Trees,
  bath: Bath,
  "shower-head": ShowerHead,
  flame: Flame,
  "shield-check": ShieldCheck,
  users: UsersRound,
  baby: Baby,
  accessibility: Accessibility,
  "map-pin": MapPin,
  "credit-card": CreditCard,
  ticket: Ticket,
  phone: Phone,
  clock: Clock3,
  star: Star,
  "air-vent": AirVent,
  armchair: Armchair,
  "arrow-up-down": ArrowUpDown,
  award: Award,
  "badge-check": BadgeCheck,
  ban: Ban,
  "battery-charging": BatteryCharging,
  bell: Bell,
  bike: Bike,
  "book-open": BookOpen,
  "briefcase-business": BriefcaseBusiness,
  building2: Building2,
  bus: Bus,
  camera: Camera,
  castle: Castle,
  "chef-hat": ChefHat,
  check: Check,
  "circle-help": CircleHelp,
  clapperboard: Clapperboard,
  "cloud-sun": CloudSun,
  compass: Compass,
  "concierge-bell": ConciergeBell,
  "cooking-pot": CookingPot,
  "door-open": DoorOpen,
  dumbbell: Dumbbell,
  fan: Fan,
  fence: Fence,
  flower2: Flower2,
  footprints: Footprints,
  gamepad2: Gamepad2,
  gift: Gift,
  "glass-water": GlassWater,
  globe2: Globe2,
  handshake: Handshake,
  heart: Heart,
  "heart-pulse": HeartPulse,
  heater: Heater,
  house: House,
  "ice-cream-cone": IceCreamCone,
  "key-round": KeyRound,
  "lamp-desk": LampDesk,
  laptop: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  "lock-keyhole": LockKeyhole,
  luggage: Luggage,
  mail: Mail,
  map: Map,
  martini: Martini,
  microwave: Microwave,
  music2: Music2,
  navigation: Navigation,
  package: Package,
  "paw-print": PawPrint,
  plane: Plane,
  plug: Plug,
  refrigerator: Refrigerator,
  sailboat: Sailboat,
  search: Search,
  ship: Ship,
  "shopping-bag": ShoppingBag,
  smartphone: Smartphone,
  sofa: Sofa,
  soup: Soup,
  speaker: Speaker,
  sun: Sun,
  thermometer: Thermometer,
  train: Train,
  trash2: Trash2,
  truck: Truck,
  umbrella: Umbrella,
  video: Video,
  "washing-machine": WashingMachine,
  wind: Wind,
  wine: Wine,
  zap: Zap,
  activity: Activity,
  "alarm-clock": AlarmClock,
  anchor: Anchor,
  backpack: Backpack,
  "badge-percent": BadgePercent,
  "bed-single": BedSingle,
  beer: Beer,
  "bell-ring": BellRing,
  binoculars: Binoculars,
  cake: Cake,
  "calendar-days": CalendarDays,
  "calendar-check": CalendarCheck,
  car: Car,
  "car-taxi-front": CarTaxiFront,
  "check-circle2": CheckCircle2,
  "circle-parking": CircleParking,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  coins: Coins,
  croissant: Croissant,
  "cup-soda": CupSoda,
  "door-closed": DoorClosed,
  droplets: Droplets,
  fish: Fish,
  flag: Flag,
  flashlight: Flashlight,
  fuel: Fuel,
  "gallery-horizontal": GalleryHorizontal,
  "hand-heart": HandHeart,
  "hand-platter": HandPlatter,
  headphones: Headphones,
  "heart-handshake": HeartHandshake,
  hotel: Hotel,
  hourglass: Hourglass,
  image: Image,
  info: Info,
  "key-square": KeySquare,
  "lamp-ceiling": LampCeiling,
  "lamp-floor": LampFloor,
  languages: Languages,
  library: Library,
  "life-buoy": LifeBuoy,
  lock: Lock,
  "map-pinned": MapPinned,
  medal: Medal,
  megaphone: Megaphone,
  moon: Moon,
  "package-check": PackageCheck,
  palmtree: Palmtree,
  "party-popper": PartyPopper,
  "pen-line": PenLine,
  percent: Percent,
  "person-standing": PersonStanding,
  "piggy-bank": PiggyBank,
  pizza: Pizza,
  popcorn: Popcorn,
  presentation: Presentation,
  printer: Printer,
  projector: Projector,
  radio: Radio,
  receipt: Receipt,
  recycle: Recycle,
  "refresh-ccw": RefreshCcw,
  rocket: Rocket,
  route: Route,
  salad: Salad,
  "scan-face": ScanFace,
  scissors: Scissors,
  "scroll-text": ScrollText,
  send: Send,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  signal: Signal,
  siren: Siren,
  "sliders-horizontal": SlidersHorizontal,
  smile: Smile,
  sprout: Sprout,
  "square-check": SquareCheck,
  stethoscope: Stethoscope,
  store: Store,
  sunset: Sunset,
  table: Table,
  tag: Tag,
  telescope: Telescope,
  tent: Tent,
  theater: Theater,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  toilet: Toilet,
  "train-front": TrainFront,
  "tram-front": TramFront,
  "tree-pine": TreePine,
  trophy: Trophy,
  "user-check": UserCheck,
  wallet: Wallet,
  warehouse: Warehouse,
  wrench: Wrench,
};

export function roomAmenityIcon(
  iconKey: string | null | undefined,
): LucideIcon {
  return iconKey ? (icons[iconKey] ?? ShieldCheck) : ShieldCheck;
}
